### ISSUE TITLE
Secret files are updated by reconfigure and will always change

### ISSUE THREAD

**Issue by Aethylred** [Aethylred/ansible-role-gitlab#1]
From GitLab 14 onwards the value of `private_api_secret_key` in `gitlab_kas` is updated whenever `gitlab-ctl reconfigure` is run. This means that whenever a secrets file is provided via the `gitlab_secrets_file` variable will always trigger a change, and the restart handler, and make the role no longer idempotent.

Setting secrets using `gitlab_secrets_file` should be continued for legacy purposes, but consider switching to using a 

```
gitlab_secrets:
  gitlab_kas:
    api_secret_key: 'key value'
    private_api_secret_key: 'key value'
```

However this may depend on the exact behaviour of `gitlab-ctl reconfigure` and we might need to figure out how to get Ansible to ignore changes to this line.
