### ISSUE TITLE
GitLab 15 change to config file for database configuration

### ISSUE THREAD

**Issue by Aethylred** [Aethylred/ansible-role-gitlab#2]
From GitLab 15 onward the config for the database is allows multiple databases similar to the changes for LDAP

https://docs.gitlab.com/ee/update/index.html#1500

Will need to update the multiconfig for GitLab 15 onwards to handle this. Suggest implementing a hash

```
gitlab_database:
  main:
    adapter: postgresql
    encoding: unicode
    databale: gitlab_production
```
